In [6]:
import pandas as pd

# Load dataset properly
df = pd.read_csv("Iris.csv", header=None)

# Assign correct column names (NO slicing)
df.columns = ['SepalLengthCm', 'SepalWidthCm',
              'PetalLengthCm', 'PetalWidthCm', 'Species']

df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
df.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [8]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [9]:
#create subsets for diffrenet Species
# Subset for Iris-setosa
setosa_df = df[df['Species'] == 'Iris-setosa']

# Subset for Iris-versicolor
versicolor_df = df[df['Species'] == 'Iris-versicolor']

# Display
setosa_df.head()
versicolor_df.head()

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
50            7.0           3.2            4.7           1.4  Iris-versicolor
51            6.4           3.2            4.5           1.5  Iris-versicolor
52            6.9           3.1            4.9           1.5  Iris-versicolor
53            5.5           2.3            4.0           1.3  Iris-versicolor
54            6.5           2.8            4.6           1.5  Iris-versicolor

In [10]:
# Merge both subsets
merged_df = pd.concat([setosa_df, versicolor_df])

merged_df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [11]:
# Sort in ascending order
sorted_df = df.sort_values(by='PetalLengthCm', ascending=True)

sorted_df.head()

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
22            4.6           3.6            1.0           0.2  Iris-setosa
13            4.3           3.0            1.1           0.1  Iris-setosa
14            5.8           4.0            1.2           0.2  Iris-setosa
35            5.0           3.2            1.2           0.2  Iris-setosa
16            5.4           3.9            1.3           0.4  Iris-setosa

In [12]:
# Transpose rows to columns
transposed_df = df.T

transposed_df.head()

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
SepalLengthCm,5.1,4.9,4.7,4.6,5.0,5.4,4.6,5.0,4.4,4.9,...,6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9
SepalWidthCm,3.5,3.0,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,...,3.1,3.1,2.7,3.2,3.3,3.0,2.5,3.0,3.4,3.0
PetalLengthCm,1.4,1.4,1.3,1.5,1.4,1.7,1.4,1.5,1.4,1.5,...,5.6,5.1,5.1,5.9,5.7,5.2,5.0,5.2,5.4,5.1
PetalWidthCm,0.2,0.2,0.2,0.2,0.2,0.4,0.3,0.2,0.2,0.1,...,2.4,2.3,1.9,2.3,2.5,2.3,1.9,2.0,2.3,1.8
Species,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,...,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica

In [13]:
#melt data
# Convert wide format to long format
melted_df = pd.melt(df,
                    id_vars=['Species'],
                    value_vars=['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm'],
                    var_name='Feature',
                    value_name='Value')

melted_df.head()

       Species        Feature  Value
0  Iris-setosa  SepalLengthCm    5.1
1  Iris-setosa  SepalLengthCm    4.9
2  Iris-setosa  SepalLengthCm    4.7
3  Iris-setosa  SepalLengthCm    4.6
4  Iris-setosa  SepalLengthCm    5.0

In [14]:
#Pivot data
# Convert long format back to wide format
wide_df = melted_df.pivot_table(index='Species',
                               columns='Feature',
                               values='Value',
                               aggfunc='mean')

wide_df

Feature          PetalLengthCm  PetalWidthCm  SepalLengthCm  SepalWidthCm
Species
Iris-setosa              1.464         0.244          5.006         3.418
Iris-versicolor          4.260         1.326          5.936         2.770
Iris-virginica           5.552         2.026          6.588         2.974